### ISSUE TITLE
Bad Mail verified?

### ISSUE THREAD

**Issue by heikokrebs** [egulias/EmailValidator#114]
I have a problem with Inputs like ```'info@test.com'``` or ```info@test.com'``` - note the apostrophes.

These are not valid mail addresses?

**Comment by egulias** [comment]
They are valid, probably with warnings. Which version are you using? V2 tests pass with both emails.

**Comment by heikokrebs** [comment]
@egulias i am using v1.2
But are such mail really valid? I tested some mail services and all didnt send them, gave me an error.

**Comment by egulias** [comment]
They are indeed rare, so it really depends on the mail service. You can use `isValid("email", false, true)` which **will not** check DNS and **will** return false if there is at least one warning, making those emails be "invalid"
