### ISSUE TITLE
Add EmailValidatorInterface in 2.x

### ISSUE THREAD

**Issue by cilefen** [egulias/EmailValidator#121]
See #120

**Comment by egulias** [comment]
Hi @cilefen 
I was wondering, why is not enough with `https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Validation/EmailValidation.php` interface? There you can implement and use your very own validation. Would be like having your own validation within the validator.

**Comment by cilefen** [comment]
That sounds very interesting. I updated the Drupal issue about this feature.
