### ISSUE TITLE
E-Mails with german Umlaute

### ISSUE THREAD

**Issue by HKandulla** [egulias/EmailValidator#129]
Hi, I am using EmailValidator (1.2) as part of a Symfony project. EmailValidator accepts emails with german Umlaute like (hannes.möller@gmail.com) but Swiftmailer throws an exception when used as recipient. Is this a bug on EmailValidator or Swiftmailer? 
Thanks, Hannes

**Comment by HKandulla** [comment]
Ok. After reading up on this, I understand that this is a bug in SwiftMailer and will only be fixed in the upcomming 6th. version which uses EmailValidator ~2.0.

**Comment by egulias** [comment]
Hi @HKandulla I was just to answer you that same thing :)

**Comment by HKandulla** [comment]
Hi @egulias, thanks for responding and big thanks for all your work! I will go with this [quickfix](https://github.com/symfony/symfony/issues/19359) in the meantime.

**Comment by webdevilopers** [comment]
Hello @HKandulla ,
I recently started using this lib for Symfony 5. And emails e.g. "daniel.brödje@gmail.com" are still valid.
We use *^2.1* and `symfony/swiftmailer-bundle` *^3.4*.

Can you reference any issue on this on the swiftmailer project?

**Comment by webdevilopers** [comment]
Sorry, it looks like I was misunderstanding the original ticket. It seems as if emails e.g. "daniel.brödje@gmail.com" are indeed regarded valid?

AFAIK umlauts are allowed in the domain name but I was not aware of them being accepted inside the email address itself. Can anybody confirm this?

**Comment by webdevilopers** [comment]
Just found this:

> The following are all valid international email addresses:
> Dörte@Sörensen.example.com  (German, Unicode)

* https://en.wikipedia.org/wiki/International_email#Email_addresses

**Comment by egulias** [comment]
Hello @webdevilopers , 
that's correct. According to [RFC6530](https://tools.ietf.org/html/rfc6530) emails can have UTF-8 chars in the body.
