### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dereuromark** [egulias/EmailValidator#130]
For those not too experienced with what SpoofCheck or NoRfcWarning would actually do, and what the pitfalls or possible false positives could be, it can be rather confusing.
Each validator is a bit under-documented at the moment.
It would be good to have a small human readable paragraph to each of them either in the readme or some dedicated documentation.

**Comment by egulias** [comment]
Yes, I agree.
BTW, do you think cakephp could benefit from this validator?

**Comment by dereuromark** [comment]
As a plugin i would definitly say so.
Unfortunately my Tests so far very false positive.
An invalid Email got marked as valid with this tool.

**Comment by egulias** [comment]
Would you mind providing those false positives to improve the lib?

**Comment by dereuromark** [comment]
Maybe we can discuss that via email? Don't want to publish those here. You can find mine on my profil/blog etc. Thanks!

**Comment by 2ndGAB** [comment]
@dereuromark Are you implementing it as CakePHP plugin?

**Comment by kevindb** [comment]
I would also like to request clarification on what the strategies are. I cannot figure out which I want to use between the available validations. In particular, RFCValidation and NoRFCWarningsValidation. Even just a one sentence description of each would be helpful!
