### ISSUE TITLE
Email existence validation

### ISSUE THREAD

**Issue by egulias** [egulias/EmailValidator#131]
As a validation that checks for the existence of a given mailbox, not just the availability of the server to respond to SMTP request. E.g https://github.com/elliotttf/valid-mails

**Comment by skynet** [comment]
Are you actually working on this? Most (paid) validation services do check with SMTP server for each email address.

example: https://mailboxlayer.com/

**Comment by egulias** [comment]
Hi @skynet  ,
Not currently working on it. The aim of this lib is on the format side. It also allows you not to depend on a third party external paid api for validating format. 
I'll do my best to find some time to do it, but I cannot promise anything as the 2nd baby is on it's way :)

However I'd be more than happy to review & merge a PR with the functionality if you interested in adding it.

**Comment by skynet** [comment]
Congrats for your baby! 

mailboxlayer.com is a joke. They fail to detect mailboxes that do not exist, although they claim that their system does that.

**Comment by MojoCreator** [comment]
Any progress on this enhancement to check for existence of email on server?

**Comment by egulias** [comment]
Hi @MojoCreator , no sorry. I'll start on it as soon as I can.
Happy to review PR if you are willing to collaborate.

**Comment by sparxbpoit** [comment]
respond issue

**Comment by brockfanning** [comment]
Just posting a relevant project that seems to work for this purpose: https://github.com/hbattat/verifyEmail

**Comment by egulias** [comment]
Sorry for the late response. I agree with @brockfanning  and @Laurent3170 . There´s still interest but, for now, I'll close the enhancement due to the commented drawbacks. 
Thanks all for your comments.
