### ISSUE TITLE
( ! ) Fatal error: Class 'Egulias\EmailValidator\EmailValidator' not found in G:\wamp\www\EmailValidator\index.php on line 8

### ISSUE THREAD

**Issue by imranhaitechnologies** [egulias/EmailValidator#132]
( ! ) Fatal error: Class 'Egulias\EmailValidator\EmailValidator' not found in G:\wamp\www\EmailValidator\index.php on line 8

Hi,
I've download the project in WAMP from Git Shell command. And getting the above error.

I am using the following code:

<?php

use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\DNSCheckValidation;
use Egulias\EmailValidator\Validation\MultipleValidationWithAnd;
use Egulias\EmailValidator\Validation\RFCValidation;

$validator = new EmailValidator();
$multipleValidations = new MultipleValidationWithAnd([
    new RFCValidation(),
    new DNSCheckValidation()
]);
$validator->isValid("example@example.com", $multipleValidations); //true

Please advice. 

Thanks

**Comment by issei-m** [comment]
In PHP, classes won't be loaded automatically even though you declare them in "use" clause as long as you don't use either "require" or "autoloader".
You should use Composer to install this library: https://github.com/egulias/EmailValidator#requirements

**Comment by issei-m** [comment]
@egulias This is not lib's problem. So I think this can be closed.

**Comment by egulias** [comment]
Thanks for the reminder.
