### ISSUE TITLE
Valid email with quoted local-part marked invalid

### ISSUE THREAD

**Issue by havvg** [egulias/EmailValidator#133]
An email address with quoted string in the `local-part` evaluates as invalid, if it contains an `@`.

For example: `"foo@bar"@example.com` is a valid email address, where `foo@bar@example.com` is not, as the `local-part` is not quoting the special characters.

**Comment by issei-m** [comment]
It's about v1.2? v2.0 or later seems not to be so, since it has a [test case for that](https://github.com/issei-m/EmailValidator/blob/03917146de523f4ccd4164a9b57c965f160556f4/Tests/EmailValidator/Validation/RFCValidationTest.php#L87-L87).

**Comment by havvg** [comment]
I see. We are using `^2.1`. Switching from `Egulias\EmailValidator\Validation\NoRFCWarningsValidation` to `Egulias\EmailValidator\Validation\RFCValidation` makes this case working.

Thank you :)

**Comment by egulias** [comment]
Hi,
That's because a warning is triggered for that case and you were using a
stricter validation.
Cheers,
