### ISSUE TITLE
Fatal error: Class 'Egulias\EmailValidator\EmailValidator' not found in

### ISSUE THREAD

**Issue by AHKKK** [egulias/EmailValidator#141]
Hello,

I am trying to run your code on my local MAC OSX machine using MAMP from last 3 days but unable to run.
What i did is create a directory in public_html and install composer.
After installing compose i run following command 
`php composer require egulias/email-validator "~2.1"`
 Which install one folder name **vendor**

After that i download your code and paste in same directory.
after i create one PHP file name it test.php and put this code in 

```
<?php
use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\RFCValidation;
$validator = new EmailValidator();
$validator->isValid("example@example.com", new RFCValidation()); //true
```
Now when i run the test.php file in local host i got this error
`Fatal error: Class 'Egulias\EmailValidator\EmailValidator' not found in /Applications/MAMP/htdocs/EmailValidator/test.php on line 6 `

what is wrong ?
also is there any way to run this code without composer ?

Thanks
AKH

**Comment by issei-m** [comment]
You should import autoloader what composer created, first of all.

```php
<?php

use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\RFCValidation;

require __DIR__ . '/vendor/autoload.php';

$validator = new EmailValidator();
$validator->isValid("example@example.com", new RFCValidation()); //true
```

**Comment by AHKKK** [comment]
Hello,
Thanks for help and its working but the issue is its showing 1 on every email address like 
if i use this line
echo $validator->isValid("example@example.com", new RFCValidation()); //true
This will print 1
echo $validator->isValid("example111111@example11111.com", new RFCValidation()); //true
this will also print 1

how to test email that its correct or wrong like if email actually exist ?

Thanks

**Comment by xabbuh** [comment]
This library doesn't perform such a check. It only checks if the syntax of the given string cookies with the specification regarding the structure of an email address. If you want to make sure that an address does actually exist, you need to send a test mail.

**Comment by egulias** [comment]
Hello @AHKKK 
You can use the library without composer if you create a PSR-4 or PSR-0 type autoloader.
Also please remember that printing the boolean value `true` in PHP will print `1`, and not `true`.
`isValid` returns boolean `false` when the email is invalid. Both of your tests are valid emails. Try to use the emails provided in the tests suite for examples of invalid emails.
A sample code 
```php
if($validator->isValid("example@example.com", new RFCValidation())) { echo "valid";}
else {echo "invalid";}
```
The further this lib goes for checking existence of an email is by performing a DNS check with [DNSCheckValidation](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Validation/DNSCheckValidation.php) which checks for the existence of MX records, not the email box. For that you will need to wait until https://github.com/egulias/EmailValidator/issues/131 is implemented.

Cheers!
