### ISSUE TITLE
Email with ü are valid according to EmailValidator but are refused according to RFC 2822

### ISSUE THREAD

**Issue by jdespatis** [egulias/EmailValidator#144]
Hello

I'm able to valid successfully the email jürgen@foobar.de, but I get an exception when I try to send mail to this address, I get "Address in mailbox given [jürgen@foobar.de] does not comply with RFC 2822, 3.6.2."

I've used the code `$validator->isValid("jürgen@foobar.de", new RFCValidation())` to validate the email

So I guess that EmailValidator should not validate this email?
Or maybe I have missed something?

Thanks for your feedback

**Comment by jdespatis** [comment]
According to https://github.com/swiftmailer/swiftmailer/issues/419, it seems that `jürgen@foobar.de` is a valid mail, but is not currently supported by last tag of swiftmailer (5.4.6), it seems to only be supported by the master branch

Waiting for swiftmailer to support those emails (EmailValidator is integrated in swiftmailer@master), I add some regex to refuse valid international emails for now...

Maybe someone has a better option?

**Comment by egulias** [comment]
Hi @jdespatis , that's correct, Swiftmailer has EmailValidator integrated only in master (future v6).
You can try to require master branch for Swiftmailer, however I'm not sure how stable it is.

**Comment by jdespatis** [comment]
Gonna wait for a stable v6 then, as it's for a production

Thanks @egulias for your work

**Comment by egulias** [comment]
I hope v6 is tagged soon.
:smile:
