### ISSUE TITLE
Why diactrics are considered valid in Emails?

### ISSUE THREAD

**Issue by murilolobato** [egulias/EmailValidator#145]
Why diactris and characters as 'ç' are considered valid? If not even Gmail let us create accounts with those special characters?

**Comment by egulias** [comment]
Because of RFC [RFC 6530](http://www.rfcreader.com/#rfc6530) which allows for non ASCII characters.

**Comment by murilolobato** [comment]
Ok, but when using Symfony standard edition, out-of-box, SwiftMailer fails to send messages to emails with special characters.

Also, even my real app that uses sendgrid can't accomplish to send a email with a special char.

And I was wondering, is email with diactrics or special characters a thing? Maybe we could have another Validation based on other RFC's prior to RFC6530.

**Comment by egulias** [comment]
SwiftMailer 6 uses this very same validator (however is taking a bit until released, but you can check master branch). So at some point you'd have the same validation in both.
You can switch to use a "normal" RegExp via configuration.

> And I was wondering, is email with diactrics or special characters a thing?
You have Russian emails as an example. Or any other Easter Europe country. Also Asian ones.

**Comment by murilolobato** [comment]
I think the validation provided by this library is great, also RegExp validation is a option for me. And I'm using it now.

New version of SwiftMailer is stuck in development for years.

My point here, was to see if it is of interest of other people to create a new validation strategy limited to RFC 2822, so this library would work out of the box with the current SwiftMailer version bundled with Symfony Standard Edition. Also, even using sendgrid.net it is not possible to send messages to RFC6530 addresses. This maybe can be a opportunity to improve the set of validations of this library.

I also suggest rename the RFCValidation to RFC6530Validation, this would open space for an RFC2822Validation.

**Comment by egulias** [comment]
Looks like a good idea to me.  SwiftMailer incompatibility has been a major pain point for years.

However we should find a way to avoid renaming the main validation as it would mean a "major" releases (API change), something like having both `RFCValidation` and `RFC6530Validation extends RFCValidation`  could work.

**Comment by egulias** [comment]
Swiftmailer V6 now uses this email validator V2.
