### ISSUE TITLE
Validate emails with tilde (ã)

### ISSUE THREAD

**Issue by joaonice** [egulias/EmailValidator#151]
Email containing a tilde character (ã) are valid. Is this correct?

**Comment by egulias** [comment]
Hi @joaonice ,
It is valid for the extended [RFC6531](https://tools.ietf.org/html/rfc6531). For the standard one, it is not.
In V2 of the validator you can extend to crete an  RFC5321 validator if you wish.

**Comment by joaonice** [comment]
Hi @egulias. Ok, I'll try the V2 and do that.

Thank you.
