### ISSUE TITLE
Class 'Doctrine\\Common\\Lexer\\AbstractLexer' not found in /var/www/html/new/swift/EmailValidator/EmailValidator/EmailLexer.php on line 7

### ISSUE THREAD

**Issue by ssnatu** [egulias/EmailValidator#153]
I want to send email using swiftmailer for that I've installed swiftmailer (git clone https://github.com/swiftmailer/swiftmailer.git)
I also installed EmailValidator (git clone https://github.com/egulias/EmailValidator.git)

But, I'm getting the error **Class 'Doctrine\\Common\\Lexer\\AbstractLexer** not found in EmailLexer.php on line 7.
To solve this, I'd installed lexer (git clone https://github.com/doctrine/lexer.git) in EmailValidator/EmailValidator folder but, it didn't helped me, so later I deleted that lexer folder.

Can anyone please tell me, how to fix this?

My folder structure is
![screenshot from 2017-08-30 12-06-32](https://user-images.githubusercontent.com/31346079/29869647-bd0f03c0-8d7b-11e7-99bf-79db413c65cd.png)

My sendemail.php is:
![screenshot from 2017-08-30 12-14-17](https://user-images.githubusercontent.com/31346079/29869899-c60a9cae-8d7c-11e7-9a0c-8be31ac3f691.png)

**Comment by xabbuh** [comment]
As said in swiftmailer/swiftmailer#943 you need to manually set up your autoloader if you insist on not using Composer. This has nothing to do with the email validation package.

**Comment by ssnatu** [comment]
@xabbuh Could you please tell me how to set up autoloader manually? Thanks

**Comment by egulias** [comment]
Hi @ssnatu 
please refer to any online material for that.

**Comment by ssnatu** [comment]
Thanks @egulias but, I didn't find any helpful material for how to configure autoloader manually or how to use swiftmailer without composer.

**Comment by ssnatu** [comment]
@egulias Also please tell me autoloader means which autoloader. Is that composer.json file that comes with swiftmailer folder?

**Comment by xabbuh** [comment]
Writing a custom autoloader is no common task. If you want to that, will have to do some investigation in your own. Find out how to drive a filename from a fully qualified class name. Testing about the PSR-0 and PSR-4 standard recommendations may help you with that.

**Comment by ssnatu** [comment]
Thanks @xabbuh, I'll try to figure out this. Thanks again.

**Comment by hanisntsolo** [comment]
can anyone tell how to fix this ASAP?
