### ISSUE TITLE
Why is 'invalid@email' is valid email? It isn't valid email address

### ISSUE THREAD

**Issue by obivan86** [egulias/EmailValidator#164]

**Comment by issei-m** [comment]
I think the host name `email` is valid (a host name is not necessarily needed to be specified over the internet, i.e. local network), thus the mail your mentioned can be valid.
Meanwhile, you can also validate the email is correct to be delivered messages practically using DNS checking which validates whether the host is referenced over the internet, and `DNSCheckValidation` implements that.

**Comment by issei-m** [comment]
Seems duplicating with https://github.com/egulias/EmailValidator/issues/161
