### ISSUE TITLE
hello@gmail.ffr is valid

### ISSUE THREAD

**Issue by sylfabre** [egulias/EmailValidator#165]
`hello@gmail.ffr` is valid but should not as `ffr` is not a valid TLD.

You may use this list https://github.com/umpirsky/tld-list to check for the tld.

**Comment by pachico** [comment]
It, however, could be a valid host name.
I guess it depends on the checker you want to apply.
If `ffr` is not a valid TLD then you won't get a valid DNS check result, but it shouldn't be flagged as invalid by how it's composed.

**Comment by sylfabre** [comment]
Ok I understand your point.

But 99% of use cases are just classic checks for classic websites. It's like the `{` in the local part: it's allowed according to the RFC but I do not know any single person using this char in an email address.

A DNS check will detect the invalid TLD it but this validation is slow as it requires a network action.

=> A `CommonUseCaseValidation` would be useful :)

**Comment by pachico** [comment]
Correct, I think the validation as it is is correct, however, a `NonLocalEmailChecker`ish could be useful.

**Comment by egulias** [comment]
Hi both,
For DNS validation (which would be more reliable than a static list) you couls use the provides [DNSValidation](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/Validation/DNSCheckValidation.php)

Howere I think your thoughts are on the lines of #167 ? 
As I commented there I'm not sure such validation to be within the scope of the library. However, the somewhat broader  HTML5 regex for email validation could be a better fit and one more "real life" kind of validation.But then, why would you use a library that it aims to comply with the RFCs?

What do you think?

**Comment by pachico** [comment]
Hi, I guess there's not a unique solution for this. I personally see the value of complying to RFC and I wouldn't change it.
(People shouldn't assume that local domain names don't have dots).

**Comment by sylfabre** [comment]
In the end I mostly care about user experience in real world usage.

As a user, if I buy a plane ticket and forgot the dot of `@gmail.com` when registering I'm happy to hear that this wrong email complies with some RFC but I would rather expect the service to check for this missing dot instead of having trouble to receive my ticket ...

So yes DNS validation is a solution but it's a slow one whereas a check against an up-to-date list is fast.
And I understand your point that a `RealWordUsageValidation` may be out of the scope of this nice lib.
