### ISSUE TITLE
[Insight] Unused use statement should be avoided - in …/MultipleValidationWithAnd.php, line 6

### ISSUE THREAD

**Issue by Saibamen** [egulias/EmailValidator#169]
**[in EmailValidator/Validation/MultipleValidationWithAnd.php, line 6](https://github.com/egulias/EmailValidator/blob/19811e00829958f06d9bfbfeb0d0e6b7aaff3767/EmailValidator/Validation/MultipleValidationWithAnd.php#L6)**

> The class `Egulias\EmailValidator\Exception\InvalidEmail` is declared but never used. You should remove the `use` statement.

```php
<?php

namespace Egulias\EmailValidator\Validation;

use Egulias\EmailValidator\EmailLexer;
use Egulias\EmailValidator\Exception\InvalidEmail;
use Egulias\EmailValidator\Validation\Exception\EmptyValidationList;

class MultipleValidationWithAnd implements EmailValidation
{
    /**
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/22ba6692-9c02-42e5-a65d-1c5696bfffc6/analyses/31)_

**Comment by Developerayo** [comment]
#Fixed https://github.com/Developerayo/EmailValidator

**Comment by egulias** [comment]
Please make a PR then!
Thanks!

**Comment by GrahamCampbell** [comment]
This can be closed now?

**Comment by egulias** [comment]
Solved.
