### ISSUE TITLE
BC break in a patch release

### ISSUE THREAD

**Issue by 1ed** [egulias/EmailValidator#171]
There is a BC break in the 2.1.4 release https://github.com/egulias/EmailValidator/commit/8790f594151ca6a2010c6218e09d96df67173ad3#r29413290

This broke or production code because it requires intl and it was not required before. That should be reflected in composer.json.

**Comment by tomsommer** [comment]
This also breaks systems which does not support INTL_IDNA_VARIANT_UTS46, I opened #173 for this

**Comment by egulias** [comment]
Solved in #173
