### ISSUE TITLE
Using polyfill for ext-intl if 

### ISSUE THREAD

**Issue by ohartl** [egulias/EmailValidator#177]
As I stated before in #175 it could be problematic to just disable functionality when the extension is not available on the system. (We had the problem after upgrading from 2.1.4 to 2.1.5.)

Using a polyfill like https://github.com/symfony/polyfill-intl-icu could make this package work out of the box and still use the original functions from ext-intl if available. The suggestion for ext-intl in the composer.json should of course be kept.

The question is wether or not the polyfill from above or another one would make the code work.

For example the package symfony/intl does the same, see https://github.com/symfony/intl/blob/master/composer.json

**Comment by GrahamCampbell** [comment]
This issue needs re-opening. Was not fixed by #190. The spoofchecker part of the extension is not pollyfilled, as stated in https://github.com/egulias/EmailValidator/pull/231.

**Comment by egulias** [comment]
Closing per @GrahamCampbell [comment on Symfony's decision](https://github.com/egulias/EmailValidator/pull/231#issuecomment-671259002)
