### ISSUE TITLE
Discrepancies with is_email()

### ISSUE THREAD

**Issue by cs278** [egulias/EmailValidator#18]
Whilst investigating a Symfony issue (symfony/symfony#11722) I started working on comparing this library to the originals test suite. In doing so I've encountered multiple instances where this library produces a different result. There are 30 errors for syntax only checks and another 12 errors when DNS is consulted. My [results](https://gist.github.com/cs278/885545a2c923a56d6800) and ugly [git branch](https://github.com/cs278/EmailValidator/compare/isemail-tests).

/cc @brianfreytag

**Comment by egulias** [comment]
I'm now closing the issue since all of the "invalid" emails pass the test with the new API.
Please open a new one with the specific failures and I'll work on them.
PR welcome :)
Thanks for caring!
