### ISSUE TITLE
Part extraction issue

### ISSUE THREAD

**Issue by msphn** [egulias/EmailValidator#181]
The following message is separating parts incorrectly:
```protected function setParts($email)
    {
        $parts = explode('@', $email);
        $this->domainPart = $this->domainPartParser->getDomainPart();
        $this->localPart = $parts[0];
    }
```

According to rfc3696 @ is allowed if quoted or wrapped in double quotes.  

Examples:
`Abc\@def@example.com`
`"Abc@def"@example.com`

**Comment by egulias** [comment]
You're right @msphn :) . This code was a simplification to extract the parts, it has a lot of place for improvement.

**Comment by msphn** [comment]
@egulias I did same in the past :) Most of the time it works fine.

**Comment by georgringer** [comment]
`"Abc@def"@example.com` seems to be valid in latest version, FYI

**Comment by egulias** [comment]
Fixed in v3.

**Comment by nhovratov** [comment]
`Abc\@def@example.com` still doesn't seem to work

**Comment by egulias** [comment]
Hi @nhovratov , this is a 2 yars old issue. Do you mind opening a new one with your concrete incident? A failing test case would be super useful. Thanks
