### ISSUE TITLE
Unclear documentation about targeted RFC.

### ISSUE THREAD

**Issue by stefanotorresi** [egulias/EmailValidator#186]
Hello there,

It is unclear to me what RFC is being targeted here. From a glance at the code, it looks like 5321/5322 are the reference.
If that's the case, why are non-ASCII characters allowed in the local-part of the address when using the provided `RFCValidation` class? Those are only permitted by 6531.
Or am I missing something?

**Comment by egulias** [comment]
Hi @stefanotorresi !
Yes, it was not stated. Just did a push with the information: https://github.com/egulias/EmailValidator/blob/master/README.md#suported-rfcs

**Comment by stefanotorresi** [comment]
Thanks for the update!

Would you be interested in a PR that proposes different validation classes for different RFCs? My main use-case is that I'd like to validate against just 5321/5322, not 6531; i.e. the validator wouldn't allow non-ASCII characters. I think it should be easy enough to add some more warnings to the parser, what do you think?

**Comment by egulias** [comment]
Would be interesting of course. 
However adding warnings for the sake of the different RFC's would clutter the code. 
Also you need to check for other restrictions (e.g does RFC5321/5322 allow for comments? parenthesis? ) besides the ASCII ones.

For ASCII alone we could do something like:

1. Make [`EmailLexer`](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/EmailLexer.php) and interface and expose the dependency in [`EmailValidator`](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/EmailValidator.php#L25). It has to be done backward compatible, with the standard lexer by default.
2. Implement `RFC532xEmailLexer` removing utf8 chars and testing for ASCII alone (see [here](https://github.com/egulias/EmailValidator/blob/master/EmailValidator/EmailLexer.php#L138))

With that you could do this 
```php
use Egulias\EmailValidator\RFC532xEmailLexer;
use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\RFCValidation;

$validator = new EmailValidator(new RFC532xEmailLexer());
$validator->isValid("examplë@example.com", new RFCValidation()); //false
```
for a validation closer to RFC532x , you'd have to re-implement Local and Domain part parsers.

**Comment by arena94** [comment]
Hello,
I am not a specialist but i think it would be very usefull for any basic delopper (like me) to have three levels of RFCValidation

- RFC282x for basic email adresses
- RFC532x
- RFC653x  => SMTPUTF8 support mandatory

Regards and Happy New Year
