### ISSUE TITLE
Why email like "abc‐xxx@domain.com" is valid?

### ISSUE THREAD

**Issue by ywcdiao** [egulias/EmailValidator#187]
I am using version 1.2.15.

`$result = $emailValidator->isValid('abc‐xxx@domain.com', false, true);`

Here "‐" is not a normal hyphen "-". This email should be invalid, but the $result returns true.

Is this a bug?

**Comment by egulias** [comment]
Hi @ywcdiao!
What kind of hyphen are you using? I see no difference, maybe you can share the unicode code? Are you passing in the string the invalid type of hyphen? Maybe you have to encode/decode the hypen?

**Comment by jfinstrom** [comment]
http://www.codetable.net/decimal/8208

**Comment by egulias** [comment]
Then which is the difference?
