### ISSUE TITLE
Email *address*

### ISSUE THREAD

**Issue by szepeviktor** [egulias/EmailValidator#196]
Could you emphasize that it is an email **address** validator at several places?

PHP Email validator library -> PHP Email address validator library

**Comment by issei-m** [comment]
Pull Request is always welcome :)

**Comment by szepeviktor** [comment]
This needs to be set by hand

![kép](https://user-images.githubusercontent.com/952007/56748076-76041f80-677f-11e9-9821-e899380c39dc.png)

**Comment by issei-m** [comment]
I see.

**Comment by egulias** [comment]
Hi @szepeviktor , sorry for the delay. You mean emphasizing the addres part because of lack of validation in other regards of emails, like mailbox #194 ? Which other are you missing?

**Comment by szepeviktor** [comment]
I think email means the message itself. Mailbox is a collection of messages, and email address is just an address.

**Comment by egulias** [comment]
Well, you have a point there :). Truth is that now one has ever pointed that out. Will do I guess.
Thanks!

**Comment by egulias** [comment]
Done :)

**Comment by szepeviktor** [comment]
Thank you.
