### ISSUE TITLE
v1.2.2 Symfony Issues

### ISSUE THREAD

**Issue by brianfreytag** [egulias/EmailValidator#20]
@egulias Thank you very much for patching the bug, however, this introduced another (minor) bug into the Symfony integration.

It appears you're adding these special character (double quotes, escaping) to the warnings array. In Symfony, when you add `strict = true` into the constraint, it passes the strict variable into the library, which returns warnings as an error.

If somebody has the brian\ freytag@gmail.com e-mail address, in Symfony, it will fail out, where it should be a valid e-mail address.

The good news is the local parts that we were getting errors from are no longer being accepted. 

I don't know if this was by design, but I think we need to rethink how EmailValidator will return double quotes and escaped. Should those be warnings or just allowed?

Thanks!

**Comment by natechicago** [comment]
@egulias I recently opened a similar issue -- https://github.com/symfony/symfony/issues/18156  -- on the Symfony side of things.  Would you mind providing your opinion regarding whether or not a change should be made in how Symfony uses your library (strict vs. non-strict mode)?

**Comment by egulias** [comment]
Sure, thanks for caring.
