### ISSUE TITLE
Emailadress Herr@ is valid

### ISSUE THREAD

**Issue by GertjanBrouwer** [egulias/EmailValidator#201]
When validating the emailaddress `Herr@ ` it returns valid. Notice the space after the @-sign.

**Comment by rolinbos** [comment]
I noticed this as well.

**Comment by egulias** [comment]
Thanks for reporting. 
Please see https://github.com/egulias/EmailValidator/commit/128cc721d771ec2c46ce59698f4ca42b73f71b25

Released in v2.1.9
