### ISSUE TITLE
Words after domain part passes validation

### ISSUE THREAD

**Issue by brianfreytag** [egulias/EmailValidator#21]
We received another error for an e-mail address passing validation:

```brianfreytag@gmail.com    test```

This will happen if a user copies and pastes their e-mail address from some sort of document with words after it, and they aren't paying attention.

This e-mail should NOT pass validation.

Thanks again @egulias!

**Comment by egulias** [comment]
Hi @brianfreytag 
please see https://github.com/egulias/EmailValidator/blob/master/tests/egulias/Tests/EmailValidator/EmailValidatorTest.php#L72 
I'll close this. If you find any problem, please re open or open a new one with a failing test.
