### ISSUE TITLE
SplObjectStorage not found

### ISSUE THREAD

**Issue by pavarnos** [egulias/EmailValidator#211]
Trying to track down a weird issue running symfony/mailer in a background (supervisord) task.

About 1 in 100 jobs fail with this stack trace
```
Exception: Class 'SplObjectStorage' not found #0 vendor/egulias/email-validator/EmailValidator/Validation/RFCValidation.php(28): Egulias\EmailValidator\EmailParser->__construct(Object(Egulias\EmailValidator\EmailLexer))
#1 vendor/egulias/email-validator/EmailValidator/EmailValidator.php(37): Egulias\EmailValidator\Validation\RFCValidation->isValid('noreply@link2se...', Object(Egulias\EmailValidator\EmailLexer))
#2 vendor/symfony/mime/Address.php(43): Egulias\EmailValidator\EmailValidator->isValid('noreply@link2se...', Object(Egulias\EmailValidator\Validation\RFCValidation))
#3 vendor/symfony/mime/Address.php(78): Symfony\Component\Mime\Address->__construct('noreply@link2se...')
...
```

The weird thing is, 
* SplObjectStorage is definitely there (I checked a couple of different ways)
* it is intermittent: the other 99  are fine

Wondered if you have seen anything like this before?
You are welcome to close the ticket if you think it irrelevant to this component.

**Comment by SignpostMarv** [comment]
this was possibly picked up in #190 @ a502159b101380a2de8507c0cc67d177fe23cfa3, as it seems it wasn't being used for it's intended purpose.

**Comment by pavarnos** [comment]
thanks!
