### ISSUE TITLE
E_NOTICE Array offset Laravel 5.8

### ISSUE THREAD

**Issue by arcaela** [egulias/EmailValidator#212]
ErrorException thrown with message "Trying to access array offset on value of type null"
/homepages/31/d750175303/htdocs/app/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php:147

**Comment by driesvints** [comment]
Currently happening in the 7.4 build: https://travis-ci.org/laravel/framework/jobs/579764601

**Comment by driesvints** [comment]
This was fixed by https://github.com/egulias/EmailValidator/pull/203 apparently
