### ISSUE TITLE
Composer update for Laravel 5.8 failed on 2.1.10 => 2.1.11

### ISSUE THREAD

**Issue by nestesitio** [egulias/EmailValidator#213]
Package operations: 0 installs, 6 updates, 0 removals
  - Updating egulias/email-validator (2.1.10 => 2.1.11): The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 959

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 959

**Comment by GrahamCampbell** [comment]
@egulias This can be closed. Not related to this package.
