### ISSUE TITLE
E-Mail with space before hyphen passes RFCValidation

### ISSUE THREAD

**Issue by michilehr** [egulias/EmailValidator#217]
An email address with a space before hyphen in the local part passes the RFCValidation.

Example: firstname -lastname@gmail.com

**Comment by spenwall** [comment]
I am getting the same thing with a period instead of a hyphen.

example firstname .lastname@gmail.com

It produces the warning: `Folding whites space followed by folding white space`

**Comment by egulias** [comment]
Solved in 2.1.22
