### ISSUE TITLE
Hard crash in PHP 7.4

### ISSUE THREAD

**Issue by bobrundle** [egulias/EmailValidator#234]
Validating any email address in PHP 7.4 raises exception "Trying to access array offset on value of type null" in Parser.php at line 147

        if ($previous['type'] === EmailLexer::S_BACKSLASH

This is result of $previous being null for first character in string and new PHP 7.4 behavior "Trying to use values of type null, bool, int, float or resource as an array (such as $null["key"]) will now generate a notice"

Fix is to check for null...

        if ($previous != null && $previous['type'] === EmailLexer::S_BACKSLASH

**Comment by egulias** [comment]
See #228

**Comment by rimbaborne** [comment]
thankz

**Comment by GeneralisAblon** [comment]
366644

**Comment by GeneralisAblon** [comment]
thankz

**Comment by ricardo** [comment]
thankz

I ran `composer update` and it fixed the issue.

**Comment by carlo-quiamco** [comment]
salamat <3

**Comment by Aklnegale** [comment]
This is what you want to write. Watch the format!!       if ($previous != null && $previous['type'] === EmailLexer::S_BACKSLASH
