### ISSUE TITLE
DNSCheckValidation returning valid true for email "0"

### ISSUE THREAD

**Issue by nizamani** [egulias/EmailValidator#235]
Class Egulias\EmailValidator\Validation\DNSCheckValidation is returning email "0" as valid email, for some reason DNS check is passing when email is "0", I perform validation check using following code:

`$isEmailValid = $dnsCheckValidation->isValid($email, new EmailLexer());`

In above example $isEmailValid is returned as true and "0" becomes a valid email address.

**Edited on 10:51 2/20/2020 (GMT +5)**
Egulias\EmailValidator\Validation\DNSCheckValidation isValid() also returns true for these email addresses:
**new.email**
**email.com**

**Comment by egulias** [comment]
Fixed in v3.
Can you please confirm that this still fails in latest v2 (2.1.25)?

**Comment by egulias** [comment]
Tested, should be fixed in 2.1.25.
