### ISSUE TITLE
Strict Length Validation for Local is valid when split by numbers

### ISSUE THREAD

**Issue by henrydennis-sonin** [egulias/EmailValidator#236]
Using the laravel form validation set to strict mode we are coming accross an issue with length checking.

It seems like numbers chars are acting as a divider causing the the second half to validate successfully as it's then under the char limit.

**Case 1**
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@example.com
Expected: Invalid
Result: Invalid

**Case 2**
a5aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@example.com
Expected: Invalid
Result: Valid

**Case 3**
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@example.com
Expected: Valid
Result: Valid

**Comment by egulias** [comment]
Hi @henrydennis-sonin , thanks for reporting.
Tha's a weird bug! 
Would you mind submitting a failing unit test with the second case please?

**Comment by henrydennis-sonin** [comment]
Hey @egulias. Just looked at creating the test. Unfortunatly I cannot replicate the failing issue through unit tests. Perhaps it is an issue with laravel's integration.

**Comment by marmichalski** [comment]
I believe this has been fixed in: https://github.com/egulias/EmailValidator/pull/233/files
