### ISSUE TITLE
email is available

### ISSUE THREAD

**Issue by Mo-0hammed** [egulias/EmailValidator#238]
When I check my email is available
But this gives me true
Supposed gives me false because it is available
My code:
```
<?php
require_once 'vendor/autoload.php';
use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\DNSCheckValidation;
use Egulias\EmailValidator\Validation\MultipleValidationWithAnd;
use Egulias\EmailValidator\Validation\RFCValidation;

$validator = new EmailValidator();
$multipleValidations = new MultipleValidationWithAnd([
    new RFCValidation(),
    new DNSCheckValidation()
]);
echo $validator->isValid("gold_1z5m@hotmail.com", $multipleValidations);
```

**Comment by egulias** [comment]
Hi!
Gives ´true´ because your email is valid && DNS records exists.
´DNSCheckValidation´ returns ´true´ for valid ones.

**Comment by Mo-0hammed** [comment]
Which means cancel DNSCheckValidation ?

**Comment by egulias** [comment]
Thanks for yout patience.
Why should the result be false?

**Comment by Nacoma** [comment]
Are you thinking that it will tell you if the individual email address is a valid/existing email address? The DNSCheckValidation is only checking that the host portion is valid/exists.

**Comment by mlocati** [comment]
It's not possible to determine if an email address actually exists.
What can be done (and can be done by using this EmailValidator project) is:

1. check that an email address is syntactically correct
2. the domain (the part after the `@`) is associated to a valid MX DNS record, meaning that there should be a mail server that handles these emails
