### ISSUE TITLE
Why email bla@example.com+bla is valid?

### ISSUE THREAD

**Issue by Kifir22** [egulias/EmailValidator#239]

**Comment by olek07** [comment]
asdfghg@t~online.de, tssdfsdfs @ gmx.de, dfdfd@gmx# are also valid. WTF?

**Comment by ilazaridis** [comment]
even whatever@gmail is valid. :/

**Comment by mlocati** [comment]
`whatever@gmail` *is* a valid email address. See https://github.com/egulias/EmailValidator/issues/205#issuecomment-516149398

**Comment by rrjanbiah** [comment]
FWIW, single validation is not sufficient. Mailbox validation (https://github.com/egulias/EmailValidator/pull/194) is close, but still will wrongly reject corporate business email addresses

**Comment by egulias** [comment]
Hi, 
main concerns regarding domains have been addressed in v3 (released 2020/12/29). 
V2 was following only email RFCs, in which domain part was treated very loosely. In v3 the approach is to follow RFC1030 ("internet domains" RFC).
So please upgrade, this won't be solved in v2.
