### ISSUE TITLE
Why email 'autoap@tech1com' is valid ?  

### ISSUE THREAD

**Issue by MukeshSriTech9** [egulias/EmailValidator#241]
This library includes such email as valid which is not. 

A simple `filter_var("autoap@tech1com", FILTER_VALIDATE_EMAIL)` returns false for this value. 
This library being directly mapped to Symfony 3.4 for strict RFC validation is causing problems for email validation. 

A similar value is also mentioned as valid email in `https://github.com/egulias/EmailValidator/blob/master/Tests/EmailValidator/Validation/RFCValidationTest.php` at line 78 :  `['example@localhost']` .

Please fix asap.

**Comment by Nacoma** [comment]
> admin@mailserver1 (local domain name with no TLD, although ICANN highly discourages dotless email addresses[13])

https://en.wikipedia.org/wiki/Email_address

**Comment by mlocati** [comment]
`autoap@tech1com` *is* a valid email address. See https://github.com/egulias/EmailValidator/issues/205#issuecomment-516149398
