### ISSUE TITLE
Version 1.2.18 tagged from master branch

### ISSUE THREAD

**Issue by remicollet** [egulias/EmailValidator#243]
Looks like a bad tag...

Shouldn't this be a **2.1.18**, not a 1.2.18 ?

**Comment by remicollet** [comment]
@siwinski FYI

**Comment by egulias** [comment]
Yes, you were right. Removed and retagged.
Thanks!

**Comment by mlocati** [comment]
The tag is still there, breaking all sites that use version 1... See https://github.com/egulias/EmailValidator/releases/tag/1.2.18 and https://packagist.org/packages/egulias/email-validator#1.2.18

**Comment by mlocati** [comment]
PS: it should be enough to run `git push origin :refs/tags/1.2.18` to delete the tag on GitHub, which should trigger an update on Packagist.
