### ISSUE TITLE
Release 1.2.18 is breaking

### ISSUE THREAD

**Issue by rainerkraftmb** [egulias/EmailValidator#245]
Release 1.2.18 seems to be a mistake (tracking v2.*) and breaks v1.*

**Comment by mlocati** [comment]
See also https://github.com/egulias/EmailValidator/issues/243

**Comment by rainerkraftmb** [comment]
As @mlocati mentions in #243, the release was removed but the tag is still there and still breaking v1 uses.

**Comment by egulias** [comment]
On it.

**Comment by egulias** [comment]
Gone and done.
Thanks for reporting!

**Comment by mlocati** [comment]
https://packagist.org/packages/egulias/email-validator#1.2.18 seems to be still there: you may need to log in into packagist and delete that tag (simply by going to https://packagist.org/packages/egulias/email-validator and click the `X` near the wrong tag)

**Comment by egulias** [comment]
Good lord!
Thanks @mlocati , removed from there too.
