### ISSUE TITLE
Will gmail and/or other mailhosts block my ip?

### ISSUE THREAD

**Issue by 949mac** [egulias/EmailValidator#246]
Hello -

Should I consider the need for a proxy or rate-limiting? Do you know if anyone has been blacklisted for using this package in high-volume situations?

My initial test is ~30,000 emails. But I have a list of 450,000 that I would like to clean up

Thanks again! Beautiful package, and super easy to use.

**Comment by egulias** [comment]
Hi @949mac ,
I'm glad you liked it!
The only moment the package does a call outside is for DNS validation and I'm not aware of rate limiting. However that is beyond the package responsibility.
So if you are only validating emails without DNS check you should be fine.
