### ISSUE TITLE
Catch-all validation

### ISSUE THREAD

**Issue by rrjanbiah** [egulias/EmailValidator#248]
Only an idea. Trumail has used some nice trick to validate catch-all address https://github.com/trumail/trumail/blob/master/verifier/deliverabler.go#L193 (May check their website demo)

**Comment by egulias** [comment]
Hi!
While they would be worrisome for sure, they are probably semantically correct. The lib is for validating the address composition, not for spam check or similar features.
With this information, do you think I'd still make sense the feature on the EmailValidator?

**Comment by rrjanbiah** [comment]
@egulias Up to you. But, I believe EmailValidator is doing more than RFC semantic validation.

**Comment by egulias** [comment]
@rrjanbiah I'd like to understand your point of view. Could you please elaborate?

**Comment by rrjanbiah** [comment]
@egulias In PHP, this is the most popular package. It has more than RFC semantic validation. So, IM*H*O, below are still valid candidates:

* Catch-all #248
* Disposable email #247 
* SMTP or mailbox #183

**Comment by egulias** [comment]
Hi @rrjanbiah , 
Yes, took your suggestions and made them space in v3 of the library by adding the possibility to have "extra" validations (check the Contributing file).
While I'll do my part to add them, I'm more than happy to review and merge implementations.
