### ISSUE TITLE
DNS Validation Issue

### ISSUE THREAD

**Issue by BenHarris** [egulias/EmailValidator#249]
I hit an issue today where the DNS validation wasn't working. It looks like there is a bug in alpine Linux (I was using the php:7.4-fpm-alpine docker image), which means checkdnsrr returns true even if the domain doesn't exist. See the bug reports below:

- https://bugs.php.net/bug.php?id=78008
- https://gitlab.alpinelinux.org/alpine/aports/-/issues/7392

Whilst I appreciate this is not a bug in this library, I wonder if it might be worth switching to dns_get_record in DNSCheckValidation instead, which is unaffected, allows us the same validation and was also somewhat faster in my tests.

dns_get_record returns an array or false, so the equivalent implementation would just be to do something like `$MXresult = !empty(dns_get_record($host, DNS_MX));`

### Invalid domain test
| Function | Result | Runtime |
|-|-|-|
| `checkdnsrr('notavaliddomain.c2.', 'MX')` | bool(false) | 0.00630 |
| `dns_get_record('notavaliddomain.d2.', DNS_MX)` | array(0){} | 0.00497 |

### Valid domain
| Function | Result | Runtime |
|-|-|-|
| `checkdnsrr('google.com.', 'MX')` | bool(true) | 0.00152 |
| `dns_get_record('google.com.', DNS_MX)` | <pre>array(5) {<br>  [0]=> array(6) {<br>    ["host"]=> string(10) "google.com"<br>    ["class"]=> string(2) "IN"<br>    ["ttl"]=> int(600)<br>    ["type"]=> string(2) "MX"<br>    ["pri"]=> int(40)<br>["target"]=> string(23) "alt3.aspmx.l.google.com"<br>  }<br>  ...<br>}</pre> | 0.00115 |

**Comment by BenHarris** [comment]
Another benefit to this approach would be handling the "Null MX" case [RFC 7505](https://tools.ietf.org/html/rfc7505).

`checkdnsrr('example.com.', 'MX')` returns `bool(true)` as the MX record exists. As there is no target, it should be considered invalid and return false. `dns_get_record()` returns the DNS records, so we can simply validate that a) there is an MX record and b) it is a valid record.

**Comment by egulias** [comment]
Hi @BenHarris , 
Thanks for informing about this issue.
I see the benefits you state and i'd be a great improvement for that validation.
I encourage you to do the change and send a PR ;), I will be more than happy to review and merge.

Looking forward to that PR!

**Comment by egulias** [comment]
I'll do the port to V3.
