### ISSUE TITLE
Pipe character is allowed

### ISSUE THREAD

**Issue by koraykupe** [egulias/EmailValidator#253]
Hi,

I use RFC validation only, but it accepts | character in the local part.

e.g: `test|local@domain.com`

Why? Is it allowed regarding the RFCs indeed?

**Comment by egulias** [comment]
Hello @koraykupe , 
Yes, it is indeed allowed. RFC allows for any ASCII printable char (plus UTF-8 in following updates). See https://tools.ietf.org/html/rfc5322#section-3.2.3
