### ISSUE TITLE
New release after 2.1.18 is 2.19.0

### ISSUE THREAD

**Issue by phil-davis** [egulias/EmailValidator#254]
The release does have some new validation in it, so it might have been 2.2.0 or 2.1.19

I guess this was an accidental error, numbering the release 2.19.0

It is too late now, and does not do any harm - 2.2.* 2.3.* through 2.18.* will just never exist.

I have raised this issue just to point this out, and so that when making the next release someone will continue the numbering from here - 2.19.1... then 2.20.0 - please close this issue after acknowledging.

**Comment by egulias** [comment]
Hi @phil-davis , thanks for reporting. I'll create 2.1.19 as it is the right numbering.

**Comment by egulias** [comment]
Created https://github.com/egulias/EmailValidator/releases/tag/2.1.19 and noted in 2.19.0

**Comment by phil-davis** [comment]
@egulias there is still 2.19.0, so when I (or anyone) does an ordinary `composer update` they get 2.19.0

If 2.19.0 stays there, then future releases will need to be tagged 2.19.1 or 2.20.0 so that people actually get the upgrade.

I am not sure what you should do about this. It has only been 12 hours or so that 2.19.0 has been tagged - maybe nobody has actually made use of it yet (i.e. maybe it is not committed in any `composer.lock`) In that case you might be able to delete the tag without "breaking the internet".

If you do delete the 2.19.0 tag, I can easily cancel https://github.com/owncloud/core/pull/37789 - that might be the first place to attempt that version bump.

**Comment by egulias** [comment]
I thought I could run away with just creating 2.1.19 as per ~2.1 type of thing. I'll have to delete the tag and the version. On it. 
Thanks!

**Comment by phil-davis** [comment]
Yeh, most people have something like `^2.0` in their `composer.json` which will automagically suck in the latest minor+patch of major version 2.

**Comment by egulias** [comment]
Done.

**Comment by phil-davis** [comment]
@egulias you might have to manually delete from packagist.
https://github.com/composer/packagist/issues/213

**Comment by egulias** [comment]
🤦‍♂️ I need to automate this...
Done.
Thanks for your help.

**Comment by phil-davis** [comment]
Success:
```
composer update egulias/email-validator
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating egulias/email-validator (2.1.18 => 2.1.19): Loading from cache
```
