### ISSUE TITLE
dns_get_record(): DNS Query failed

### ISSUE THREAD

**Issue by marliotto** [egulias/EmailValidator#256]
```php
dns_get_record('test@t12est.co12m', DNS_MX + DNS_A + DNS_AAAA);
```

I got "Warning: dns_get_record(): DNS Query failed".

I suggest add @ to dns_get_record() in https://github.com/egulias/EmailValidator/blob/840d5603eb84cc81a6a0382adac3293e57c1c64c/src/Validation/DNSCheckValidation.php#L121

My environment:
- Windows 10
- PHP 7.3.12 (cli) (built: Nov 19 2019 13:58:02) ( ZTS MSVC15 (Visual C++ 2017) x64 )

**Comment by clemir** [comment]
Similarly I get "PHP Warning:  dns_get_record(): A temporary server error occurred." When it validates `dns_get_record('fjks.com', DNS_MX + DNS_A + DNS_AAAA);`

**Comment by egulias** [comment]
Hi @clemir  is yout env windows also?
Suppressing the error would be last resort, since it invalidates the whole DNS validation.

**Comment by egulias** [comment]
@marliotto in your case the question is if that domain even exist :). The fact that the query fails for an invented domain is valid, as it is actually going out to look for DNS servers

**Comment by sfilzek** [comment]
Hi, sorry to jump in on this, but I've just noticed that I'm getting failures from the same point. Happening on Windows/php 7.2.11 and Ubuntu/php 7.4.7

eg:

`$dnsRecords = dns_get_record("green.com", DNS_MX + DNS_A + DNS_AAAA); `

It seems that dns_get_record is actually raising a warning when it gets a SERVFAIL instead of returning false?

**Comment by clemir** [comment]
Hi @egulias!

> Hi @clemir is yout env windows also?
No. it's Ubuntu 18.04 and PHP 7.4.8
> Suppressing the error would be last resort, since it invalidates the whole DNS validation.
I'm using Laravel and I resolved the error creating a custom DNSCheckValidation class that catches the exception in order to return false in that case

**Comment by egulias** [comment]
Hi there,
please check #261 
It is a bug in PHP that raises an un-catchable error. Wrokaround implemented.
Please let me know if it still happens with version 2.1.20

**Comment by lptn** [comment]
hey @egulias 
The warning message is still present:
```php
 $dnsRecords = dns_get_record('nyccfb.info', DNS_MX);
// PHP Warning:  dns_get_record(): A temporary server error occurred. in /path/to/script
```

Package version: [2.1.21](https://github.com/egulias/EmailValidator/releases/tag/2.1.21)
PHP Version 7.4.4 FPM/FastCGI

php.ini
```ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

**Comment by egulias** [comment]
Hi @lptn 
That's weird. Code in that version is (https://github.com/egulias/EmailValidator/blob/master/src/Validation/DNSCheckValidation.php#L119 )
$dnsRecords = @dns_get_record($host, DNS_MX + DNS_A + DNS_AAAA);`
Looks like you are doing the test withoout the `@` to supress errors, PHP's `dns_get_record` internal function has a bug https://bugs.php.net/bug.php?id=73149 .

**Comment by lptn** [comment]
Hey @egulias 
I also surprised how PHP behaves in this case. This is a screenshot from a Tinker REPL:

![image](https://user-images.githubusercontent.com/5278175/94677854-43703600-0326-11eb-8fe6-8bc631ab3117.png)

It seems like the behaviour depends on PHP settings, but I couldn't find which ones

**Comment by egulias** [comment]
Hi @lptn , thanks for the follow up. 
It is surprising. Maybe it has to do with a config related to the `@` behaviour and eliminating it?
I've done a quick search but nothing apparent.

How could we catch that error if suppression fails?

**Comment by lptn** [comment]
@egulias 
I've checked my php.ini and haven't find anything suspicious. Currently, I even don't know where to dig... Do you have any ideas?
