### ISSUE TITLE
PHP Error on this library

### ISSUE THREAD

**Issue by joseph-cs** [egulias/EmailValidator#259]
Hi ! When we use your library we get this error...

PHP error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /var/www/html/jos/vendors/EmailValidator/EmailValidator.php at 4

**Comment by xabbuh** [comment]
Can you show the full contents of the `/var/www/html/jos/vendors/EmailValidator/EmailValidator.php` file?

**Comment by joseph-cs** [comment]
Thanks for your response. It was a default line added by our application in the beginning. Not a fault of this library.
