### ISSUE TITLE
dns_get_record(): A temporary server error occurred.

### ISSUE THREAD

**Issue by CarlAtIssl** [egulias/EmailValidator#260]
Hi

When we use this check on an invalild email address, we get the following exception emailed to us:

** Message **
dns_get_record(): A temporary server error occurred.

** File **
DNSCheckValidation.php

** Action **
update

** Line **
121

And then get some other file references:

** Trace **

Illuminate\Foundation\Bootstrap\HandleExceptions -> handleError
DNSCheckValidation.php : 121 
dns_get_record
DNSCheckValidation.php : 107 
Egulias\EmailValidator\Validation\DNSCheckValidation -> validateDnsRecords
DNSCheckValidation.php : 80 
Egulias\EmailValidator\Validation\DNSCheckValidation -> checkDns
MultipleValidationWithAnd.php : 65 
Egulias\EmailValidator\Validation\DNSCheckValidation -> isValid
EmailValidator.php : 37 
Egulias\EmailValidator\Validation\MultipleValidationWithAnd -> isValid
ContactController.php : 876 
Egulias\EmailValidator\EmailValidator -> isValid
ContactController -> update

Any idea why this just dies and gives an exception rather than invalidating the request?

Cheers in advance
Carl.

**Comment by egulias** [comment]
hi @CarlAtIssl , thanks for reporting. 
Two bugs in one :).
First, there's a php bug: https://bugs.php.net/bug.php?id=73149 that prevents the exception to be handled. 
Second, there's no exception control within the validator itself.

There's a workaround, will implement.

Eduardo
