### ISSUE TITLE
Split non-RFC validations into a new package - pros/cons

### ISSUE THREAD

**Issue by egulias** [egulias/EmailValidator#262]
After being pointed out in some issues that the validator might be doing more than validating the email address pure syntaxis, I've got to the conclusion that this is somewhat correct.
It has the DNSValidation and the SpoofEmailValidation. And many more could fit if they were to have their own package.

Now, spliting into another package would mean additional maintenance while also allowing for new additional validations that seem to have interest within users.

What do you  think?

**Comment by nicolas-grekas** [comment]
Keep it in one package. Unless the ppl suggesting this split want to be in charge, you should decide for what makes your life morea easy, as a maintainer.

**Comment by egulias** [comment]
Thanks @nicolas-grekas , I have followed your advise.
