### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by georgringer** [egulias/EmailValidator#281]
Found an example which triggers fatal error

```
$email = '1';
$validator = new EmailValidator();
return $validator->isValid($email, new RFCValidation());
 ```
 
 expectation: it should just return false not a fatal error

**Comment by egulias** [comment]
Hello @georgringer !
For which version? I have run a test for both 3.x and 2.x and both return `false` on that string. 
Thanks!

**Comment by georgringer** [comment]
```
composer show | grep egul
egulias/email-validator                    2.1.25
```
with `PHP 7.4.3`

**Comment by egulias** [comment]
Thanks @georgringer . I have unable to repropduce this one. Can you do a PR with a failing unit test with the specific version added to the Travis matrix?

**Comment by georgringer** [comment]
hey. sorry I can't reproduce it testing it in a test file but current usage also basically does the same thing
