### ISSUE TITLE
Wrong email validation with version 2.1.25

### ISSUE THREAD

**Issue by semihkeskindev** [egulias/EmailValidator#295]
I'm using this package indirectly. I have `laravel/framework: v7.30.4`  in my composer.json and framework requires `swiftmailer/swiftmailer: v6.2.5` and swiftmailer requires this package.

Package version on lock that I'm using: 2.1.25 

I added email rule for a endpoint request.

```php
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email|max:255',
        ];
    }
```

Normally, When the endpoint got email like `semih@semih`, It return 422 response because of not valid. But It started to accept valid similar like that emails. 

I'm saving emails that i got from requests. Then sending mail. When I tried to send email, i got 400 bad request and i think that's so normal. Emails are not valid.

 ------
Until this issue will be resolved, I'm using a custom rule wrote my own and used regex https://regexr.com/5oit9 . this regex not exactly true. (You can check **Tests** tab)

Example: semihkeskindev+1@gmail.com mail should be valid but its not for this regex. (I'm open to advanced email regex)

**Comment by egulias** [comment]
Hello @semihkeskindev 
`test@toplevel` is a valid email per the RFC. However, a syntactically valid emails does not mean that the email exists. This library checks for the syntaxis.
This is how it is intended to work.
If this case is too wide for you and regex works for your use case, I'm happy for that. As a tip, I suggest you to use PHP's `filter_var` which while it has some shortcommings it is much better and requires less maintenance than a complex regex.
Cheers.
