### ISSUE TITLE
Ill-formed byte sequences should be validated

### ISSUE THREAD

**Issue by masakielastic** [egulias/EmailValidator#30]
The validator bypasses Ill-formed byte sequences. The definition of UTF-8 string can be seen in RFC 3629 or "Table 3-7. Well-Formed UTF-8 Byte Sequences" in the Unicode Standard (from [my answer](http://stackoverflow.com/a/13695364/531320) on stackoverflow).

```php
$validator = new EmailValidator;
$email = "\x80\x81\x82@\x83\x84\x85.\x86\x87\x88";

var_dump(
    true === $validator->isValid($email)
);
```
The way for validating UTF-8 string is using htmlspecialchars or preg_match.

```php
function utf8_validate($str) {
    return $str === htmlspecialchars_decode(htmlspecialchars($str, ENT_QUOTES, 'UTF-8'));
}

function utf8_validate2($str) {
    return false !== preg_match('/./u', $str);
}
```

**Comment by egulias** [comment]
@masakielastic I'll close this, please check version 1.2.7. If you find more issues, please create new ones.
Thanks!
