### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by nisancigokmen** [egulias/EmailValidator#310]
hello, how can I contact you?
,gökmen.

**Comment by egulias** [comment]
You just did :). How can I help you?

**Comment by nisancigokmen** [comment]
> You just did :). How can I help you?

_**super :D  Do you mind if I take part in a few projects with you?**_

**Comment by egulias** [comment]
What do you mean? Which projects?

**Comment by nisancigokmen** [comment]
**I want to collaborate with you. If you wish, we can discuss in detail. good works. , gökmen** @egulias
thanks:)

**Comment by egulias** [comment]
Thanks for your patience. I'm short on free time these days to engage on further open source projects. If you want to collaborate in the scope of this library, feel free to go through the issues and answer or send PRs with the fixes. I will happily review them.

**Comment by nisancigokmen** [comment]
Thanks:)
