### ISSUE TITLE
DNS record check should pass if email address has no top-level domain 

### ISSUE THREAD

**Issue by SuperDJ** [egulias/EmailValidator#338]
Right not the DNSCheckValidation check fails when an email address has no top-level domain.

**Comment by egulias** [comment]
Hi. I don't understand. Can you clarify which is the problem?

**Comment by SuperDJ** [comment]
@egulias I have noticed in your code, there are multiple checks to be made to validate an email address. One of these check if an domain has an IP-address but in some rare case an domain like "example.com" hasn't an IP but "www.example.com" has. After the first check on [#L135](https://github.com/egulias/EmailValidator/blob/3.x/src/Validation/DNSCheckValidation.php#L135) it just stops, even though the domain "example.com" has an valid MX-record.

**Comment by egulias** [comment]
Thanks for clarifying.
I see, kind of a miss configuration.
I'll flag it to be added. I'm happy to review a PR from you with a solution if it's urgent for you.

**Comment by kergekacsa** [comment]
Let's see if this helps. #355

**Comment by egulias** [comment]
Closed by https://github.com/egulias/EmailValidator/pull/355
