### ISSUE TITLE
Support Doctrine Lexer v2.x + v3.x

### ISSUE THREAD

**Issue by phramz** [egulias/EmailValidator#341]
Hey folks!
First of all thanks for this library, it does a great job so far 👍

I wonder if there are any plans to release a 4.x version any time soon, since it's getting harder to actually integrate it due to the hard dependency on Doctrine Lexer 1.x (current major 3.x). This will conflict with almost all new setups using a current version of Doctrine ORM/DBAL. 

Cheers!

**Comment by egulias** [comment]
Hey! Working on it, see #339 and #340

**Comment by phramz** [comment]
Hey @egulias! I only looked at the issues and didn't find any regarding this ... just saw the existing PRs right after opening another #342 🙈 Sorry for the duplicates ... guess I'm still a bit dizzy from the holidays XD

**Comment by egulias** [comment]
Resolved with `3.2.5` and `4.0.0`
