### ISSUE TITLE
Migration Guide V3 => V4

### ISSUE THREAD

**Issue by Chris53897** [egulias/EmailValidator#357]
Hi,
is there a migration guide for v3 => v4?
Or do users do not have to change there code?

Greetz

**Comment by abilogos** [comment]
I guess if you have php8 installed, there would be no issue there.
as I have seen the test on the 4.x branch has been failed.
I don't know if its production ready or not.
seems under production.

[commit messages](https://github.com/egulias/EmailValidator/compare/3.x...4.x)

**Comment by Chris53897** [comment]
Ok thanks. Maybe i will wait to make a PR for symfony/mailer to support v4.

**Comment by egulias** [comment]
Hi folks.
There is no other requirement than having PHP >8.1. This is to have the latest version of the main dependency and to allow the language to advance in adoption as many projects depend on this library.

The interface remains the same and if anything will evolve to be strict on types. In any other case, it will be another major version bump.

Tests are not failing, is the Scrutinizer integration that is failing but is apparently a problem on ther side with xdebug.
I'm looking for options to host tests results and coverage.

**Comment by Chris53897** [comment]
It is already merged. https://github.com/symfony/symfony/pull/48904
I will close this.
