### ISSUE TITLE
Since symfony/validator 6.2: The "loose" mode is deprecated. It will be removed in 7.0 and the default mode will be changed to "html5"

### ISSUE THREAD

**Issue by Axent96** [egulias/EmailValidator#370]
Symfony v6.2 have a update for mode field

**Comment by egulias** [comment]
Hi @Axent96, thanks for the heads up. Do you mind explaining a bit more the implications?

**Comment by Axent96** [comment]
thank you @egulias for your question. You can found more info here -> https://github.com/symfony/symfony/issues/41855

**Comment by egulias** [comment]
Hi @Axent96 , I have gone through the references and if I understand it right what is happening is that the term and validation mechanism *"loose"* is being replaced by *"html5"* one, which makes sense from my point of view. Now, this email validator is the one used for the *"strict"* mode which is not suffering changes.

Were you concerned the change affected this library?

**Comment by Axent96** [comment]
Hi @egulias, sorry for delay for my answer. Yes, I think it was my mistake. The issue can be closed. Thank you very much.

**Comment by egulias** [comment]
Thank you for caring. Appreciated.
