### ISSUE TITLE
version 1.2.6 requires doctrine/lexer dev-master

### ISSUE THREAD

**Issue by tubssp** [egulias/EmailValidator#40]
if i install the version 1.2.6 have i the following problem:

  Problem 1
    - Installation request for egulias/email-validator v1.2.6 -> satisfiable by egulias/email-validator[1.2.6].
    - egulias/email-validator 1.2.6 requires doctrine/lexer dev-master -> no matching package found.
  Problem 2
    - egulias/email-validator 1.2.6 requires doctrine/lexer dev-master -> no matching package found.
    - tubssp/aura 2.5.x-dev requires egulias/email-validator v1.2.6 -> satisfiable by egulias/email-validator[1.2.6].
    - Installation request for tubssp/aura 2.5.x-dev -> satisfiable by tubssp/aura[2.5.x-dev].

but the version 1.X of lexer ist needet from others:
  Problem 1
    - The requested package doctrine/lexer could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for tubssp/aura 2.5.x-dev -> satisfiable by tubssp/aura[2.5.x-dev].
    - tubssp/aura 2.5.x-dev requires doctrine/lexer master -> no matching package found.
  Problem 3
    - Installation request for egulias/email-validator v1.2.6 -> satisfiable by egulias/email-validator[1.2.6].
    - egulias/email-validator 1.2.6 requires doctrine/lexer dev-master -> no matching package found.
  Problem 4
    - doctrine/orm v2.4.6 requires doctrine/dbal ~2.4 -> satisfiable by doctrine/dbal[v2.4.3, v2.4.0, v2.4.1, v2.4.2].
    - doctrine/orm v2.4.6 requires doctrine/dbal ~2.4 -> satisfiable by doctrine/dbal[v2.4.3, v2.4.0, v2.4.1, v2.4.2].
    - doctrine/dbal v2.4.3 requires doctrine/common ~2.4 -> satisfiable by doctrine/common[v2.4.2, v2.4.0, v2.4.1].
    - doctrine/dbal v2.4.0 requires doctrine/common ~2.4 -> satisfiable by doctrine/common[v2.4.2, v2.4.0, v2.4.1].
    - doctrine/dbal v2.4.1 requires doctrine/common ~2.4 -> satisfiable by doctrine/common[v2.4.2, v2.4.0, v2.4.1].
    - doctrine/dbal v2.4.2 requires doctrine/common ~2.4 -> satisfiable by doctrine/common[v2.4.2, v2.4.0, v2.4.1].
    - doctrine/dbal v2.4.3 requires doctrine/common ~2.4 -> satisfiable by doctrine/common[v2.4.2, v2.4.0, v2.4.1].
    - doctrine/common v2.4.2 requires doctrine/lexer 1.* -> no matching package found.
    - doctrine/common v2.4.2 requires doctrine/lexer 1.* -> no matching package found.
    - doctrine/common v2.4.1 requires doctrine/lexer 1.* -> no matching package found.
    - doctrine/common v2.4.0 requires doctrine/lexer 1.* -> no matching package found.
    - Installation request for doctrine/orm v2.4.6 -> satisfiable by doctrine/orm[v2.4.6].

**Comment by egulias** [comment]
I'm still working on this. See http://www.doctrine-project.org/jira/browse/DCOM-264

**Comment by Seldaek** [comment]
There are two different problems IMO:

@boobooking's issue is simply an issue of package stability, dev-master of doctrine/lexer isn't found becaues your minimum-stability is stable. If you require it explicitly in your composer.json then it'll start working. Or you can lower your minimum-stability to dev but that's probably not a good idea.

The other issue of @tubssp seems to be related to your `tubssp/aura` package (I imagine that's the name of your package?) is requiring doctrine/lexer in `master` instead of `dev-master`, so that makes everything fail.

@egulias BTW you shouldn't require dev-master if you don't absolutely have to, and even if I'd say `~1.0@dev` is more future proof in case the master branch becomes 2.x

**Comment by egulias** [comment]
Thanks @Seldaek for your response.
I was previously requiring `v1.0` but there's a change in `doctrine/lexer` that was needed for issuing my own modifiers for the lexer regex, so I turned it to dev-master, but I didn't knew composer's stability would affect on this. 
Marco already answered on Twitter so I'll wait for him tagging so I can require a version number.
Again, thanks for helping :)

**Comment by egulias** [comment]
@boobooking @tubssp please require version `1.2.7` should this be fixed. Thanks!
