### ISSUE TITLE
error in readme.md, usage, advanced example

### ISSUE THREAD

**Issue by kcassam** [egulias/EmailValidator#53]
Should be (see // here!)

    use Egulias\EmailValidator\EmailValidator;

    $validator = new EmailValidator;
    $email = 'dominic@sayers.cc';
    $result = $validator->isValid($email);

    if ($result) {
        echo $email . ' is a valid email address';
    // here!
    }
    if ($validator->hasWarnings()) {
        echo 'Warning! ' . $email . ' has unusual/deprecated features (result code ' . var_export($validator->getWarnings(), true) . ')';
    } else {
        echo $email . ' is not a valid email address (result code ' . $validator->getError() . ')';
    }

**Comment by egulias** [comment]
Hi @kcassam sorry for my late response.
You are right, but if you modify like that, the `else` should go with the first `if`.
I'm thinking of improving the readme, by the way.

**Comment by egulias** [comment]
Please see #106
