### ISSUE TITLE
Not validating use of special characters in domain correctly

### ISSUE THREAD

**Issue by SamBurns-awin** [egulias/EmailValidator#57]
```php
$validator = new \Egulias\EmailValidator\EmailValidator();
var_dump($validator->isValid('email.email@email.!"£$%^&*'));
```
Expected result: false
Actual result: true

**Comment by egulias** [comment]
Hi @SamBurns-awin thanks for reporting.
From your example, only chars `£` and `"` are invalid for a domain. I've added the tests, I'll release a fix asap.
The rest are "valid" in the broad definition given by [RFC 5322 - 3.4.1](http://www.rfcreader.com/#rfc5322_line710)

**Comment by SamBurns-awin** [comment]
Thanks for your help @egulias :-)

**Comment by egulias** [comment]
@SamBurns-awin char `£` is UTF8 valid, thus initially valid for an email. I have to research some more through the RFC's to see if there's a restriction within the UTF8 chars that can be used.
If you happen to find this information, please let me know.
