### ISSUE TITLE
email with cyrillic domain are marked as invalid

### ISSUE THREAD

**Issue by boobooking** [egulias/EmailValidator#78]
Hi!

I suppose there is a problem with cyrillic domains. 

This email marked as invalid but domain and email is ok
1500111@профи-инвест.рф
http://профи-инвест.рф

**Comment by egulias** [comment]
Yes, can be. UTF'8 has to be improved. I'll add it as a test and see to fix it. Thanks for reporting.

**Comment by egulias** [comment]
Added tests to proof that is currently working.
