### ISSUE TITLE
Difference between is_email() and this library for email '$@$#$#'

### ISSUE THREAD

**Issue by borNfreee** [egulias/EmailValidator#79]
Hi,

Why this email `$@$#$#` is valid for your library with strict mode

```php
$validator->isValid('$@$#$#', false, true) // true
```
and is not valid with `is_email()` function?

```php
is_email('$@$#$#') // false
```

Is it really a valid email address?

**Comment by egulias** [comment]
It is valid in a broad manner (those are valid ASCII chars), despite having invalid DNS chars.
The `strict` flag is to mark an email as invalid if there are any warnings, which might be the bug in this case.
I'll investigate on this to see why there are no warnings and if there should be.

**Comment by borNfreee** [comment]
@egulias could you please share your investigation details?
