### ISSUE TITLE
What about Australia?

### ISSUE THREAD

**Issue by PiTiLeZarD** [egulias/EmailValidator#83]
Hi there,

I'm writing after using this module through Drupal 8. Emails in @something.com.au are marked invalid and it's kind of a big deal for us ;)

Do you think there's an easy fix to that? I didn't look into your code so far...

Thanks for your time.

**Comment by egulias** [comment]
Good point, and it is an important bug. Probably something to fix on the domain parser. Will check this asap.

**Comment by egulias** [comment]
Hey @PiTiLeZarD can you please tell me the version you are using? I've run a tests with your bug and it is working properly (latest version is [1.2.10](https://github.com/egulias/EmailValidator/releases/tag/1.2.10))

**Comment by PiTiLeZarD** [comment]
Hey egulias,

Hard to say, I'm using the one with drupal 8 rc2. The closest I got from figuring out the version was in the composer.json:

  "extra": {
    "branch-alias": {
      "dev-master": "2.0.x-dev"
    }
  },

I will update drupal first and then try an update on your lib see if it fixes it... I'm happy to hear it that its working in your version I'll try to match that!

Thanks for your answer!

**Comment by xabbuh** [comment]
@PiTiLeZarD You can see the installed package versions by running `composer show -i`.

**Comment by PiTiLeZarD** [comment]
aHA! thanks for that:
egulias/email-validator           1.2.9              A library for validating emails

**Comment by egulias** [comment]
Can you require `1.2.11` or greater and replicate the error? Test in the current versions are ok for this case.

**Comment by egulias** [comment]
Closes as it is resolved by the following patch versions.
