### ISSUE TITLE
uft8 symbols in email address like være@mail.com is valid

### ISSUE THREAD

**Issue by eugenegp** [egulias/EmailValidator#85]
But Gmail mark it as invalid and also I get message in Swiftmailer
Address in mailbox given [være@mail.com] does not comply with RFC 2822, 3.6.2.

**Comment by egulias** [comment]
Hi @eugenegp sorry for the delay.
If you check this issue (https://github.com/egulias/EmailValidator/issues/46) you will find useful information on Gmail email address validation.
Also until Swiftmailer 6, email address validations was done with complex RegExp that didn't allowed for UFT8 chars.
Please check RFC [6530](http://tools.ietf.org/html/rfc6530#section-4.6), [6531](http://tools.ietf.org/html/rfc6531), [6532](http://tools.ietf.org/html/rfc6532) that allow for **SMTPUTF8** international emails.

**Comment by jroussel** [comment]
Hello,

I'm also having trouble with email address such as "françois@test.com"
I'm using Symfony2 email validator with the "strict" option and this email is valid but SwiftMailer can not send email (same error message "Address in mailbox given [françois@test.com] does not comply with RFC 2822, 3.6.2.")

Is it something related or that can be solved?

Thank you!

**Comment by egulias** [comment]
Hi @jroussel 
the issue with SwiftMailer <=5 is that it uses RexExp to validate an email and it is not updated to allow URF8 chars in them. Starting SwiftMailer 6 it using this same library to validate the emails.

Hope this helps!

**Comment by jroussel** [comment]
OK, thank you for this information
I will seee what I can do for this particular case until SwiftMailer 6
