### ISSUE TITLE
Compatibility PHP 7

### ISSUE THREAD

**Issue by quentincurtet** [egulias/EmailValidator#86]
Hi,

In the context of a PHP migration, i want to know if this EmailValidator is compatible with PHP 7 or if it's planned.

Thanks for your answer.

Cordially.

**Comment by xabbuh** [comment]
[Tests pass on Travis CI for the PHP 7 job](https://travis-ci.org/egulias/EmailValidator/jobs/90451922).

**Comment by quentincurtet** [comment]
Thx !
