### ISSUE TITLE
example.co.uk has a valid DNS record now :)

### ISSUE THREAD

**Issue by nacc** [egulias/EmailValidator#91]
Both Debian & Ubuntu packages of php-email-validator are failing automated tests because example.co.uk no longer issues a DNSWARN_NO_RECORD for getInvalidEmailsWIthWarnings(). Changing it to example3.co.uk passes the tests again, but that seems fragile.

**Comment by oerdnj** [comment]
You know there's an RFC describing example domains and other for example IP and legacy-IP addresses.
The domain one is here: https://tools.ietf.org/html/rfc6761
Please make sure you use it when crafting tests...

**Comment by egulias** [comment]
Thanks!
I'm rewriting tests for v2, I'll backport them to v1.2 also.

**Comment by egulias** [comment]
Moved them for v2. I'll close the issue when backported for v1.2
