### ISSUE TITLE
Proposal: Add EmailAddress value object

### ISSUE THREAD

**Issue by ro0NL** [egulias/EmailValidator#93]
Hi,

What do you think of a `EmailAddress` value object, to clearify;

``` php
try {
    $email = EmailAddress::fromString('Alias+metadata@domain.COM');
    //$email = EmailAddress::fromString('Alias+metadata@domain.COM', new EmailValidator());
    //$email = new EmailAddress('Alias+metadata', 'domain.COM');
} catch (InvalidEmailAddressException $e) {
    // $e->getEmailValidator();
    echo $e->getEmailAddress() . ': ' . $e->getMessage();
    exit;
}
$email->getHost(); // "domain.COM"
$email->getLocal(); /** and/or */ $email->getAlias(); // "Alias+metadata"
$email->getMetadata(); // array('plus_sign' => 'metadata'); // not sure how this is called :)
$email->normalize()->getHost(); // "domain.com"
$email->normalize()->getAlias(); // "alias+metadata"
$email->equals($otherEmail); // true|false
(string) $email; // "Alias+metadata@domain.COM"
(string) $email->normalize(); // "alias+metadata@domain.com"
```

I think this would be a useful addition to the library...

**Comment by egulias** [comment]
Hi @ro0NL 
Nice proposal, thanks for taking the time.
How would you manage warnings? Something like `$email->getWarnings()`?
What do you think of
`$email = new EmailAddress('Alias+metadata', 'domain.COM', new EmailValidator([new RFCValidation()]));`? (I'm thinking of v2 of the lib here).

I don't fully agree with `$email->normalize()->getHost();`
What about 
```php
$host = $email->getHost(); // Host
$host->normalize(); //domain.com
(string)$host // domain.COM
```
and the same for `Local` ? So we homogenize `normalize()` behaviour.

**Comment by ro0NL** [comment]
@egulias 

` new EmailValidator([new RFCValidation()])`

I like it :) This is also being discussed at symfony for their `EmailValidator`, calling it profiles (https://github.com/symfony/symfony/pull/18428), maybe you can collaborate to speed things up, i.e. your v2 lib could then simplify the symfony email validator a lot.
___

`$email = new EmailAddress('Alias+metadata', 'domain.COM', new EmailValidator([new RFCValidation()]));`

I'm not sure the constructor needs a validator / should perform any validation, as it's a value object. I would keep it really simple;

```php
public function __construct($local, $host = null) {
    if ($host ===  null) {
        if (false === strpos($local, '@')) {
            throw new \DomainException('Malformed email: ' . $local . ' (missing @)');
        }
        list($local, $host) = explode($local, 2);
    }
    $this->local = $local;
    $this->host = $host;
}
```

A factory (method), i.e. `fromString` could perform built-in validation, ensuring a correct email is passed to the constructor. Constructing the VO yourself means you have knowledge of the data which should be valid (e.g. loaded ORM data).
___

About warnings, i'm not sure a VO object should depepd on any validation knowledge, as it's part of the validation process and the VO just represents data. I.e. you should get warnings from the validator when validating (it would be weird to __construct the VO with warnings yourself...), but I understand this requires some thought. Maybe `fromString` could work like this;

```php
public static function fromString($email, array &$warnings = null, EmailValidator $validator = null) {
    // not sure about the EmailValidator internals, but you get the point
    $validator = $validator ?: new EmailValidator();
    $valid = $validator->isValid($email);
    $warnings = $validator->getWarnings();
    unset($warnings); //reference
    if (!$valid) {
        throw new InvalidEmailException($email, $validator);
    }

    return new static($email); // perhaps decompose $email instead of in the constructor
```
___

Last; the normalization thingy. What i meant was a fluent interface;

```php
public function normalize() {
     $local = mb_strtolower($this->local); // whatever normalization is needed
     $host = mb_strtolower($this->host); // whatever normalization is needed

    return new self($local, $host);
}
```

I think individual email part VO's (`LocalPart`, `HostPart`, `EmailPartInterface`) would be over-enginering the address VO. Perhaps the normalization itself could be moved to a dedicated class (`EmailNormalizer`).

**Comment by ro0NL** [comment]
About naming..i alwast thought it was;
```
foo.bar.com:80 = host
foo.bar.com = hostname
foo = domain
bar = domain
com = domain
```
and therefor the correct keyword should be `hostname`, however im reading some specs now which is pretty confusing :) but i think `domain` will do just fine and is probably correct anyway :/ as long as its consistent.
